# There is a production deployment planned for next week. The Nautilus DevOps team wants to test the deployment update and 
# rollback on Dev environment first so that they can identify the risks in advance. Below you can find more details about the plan they want to execute.



# Create a namespace xfusion. Create a deployment called httpd-deploy under this new namespace, 
# It should have one container called httpd, use httpd:2.4.28 image and 4 replicas. The deployment should use RollingUpdate strategy with maxSurge=1, and 
# maxUnavailable=2. Also create a NodePort type service named httpd-service and expose the deployment on nodePort: 30008.


# Now upgrade the deployment to version httpd:2.4.43 using a rolling update.


# Finally, once all pods are updated undo the recent update and roll back to the previous/original version.

# k create ns xfusion

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: xfusion
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4.28

#Upgrade Deployment to httpd:2.4.43
# kubectl set image deployment/httpd-deploy httpd=httpd:2.4.43 --namespace=xfusion

# Monitor Deployment Status
# kubectl rollout status deployment/httpd-deploy --namespace=xfusion

# Rollback Deployment to Previous Version
# kubectl rollout undo deployment/httpd-deploy --namespace=xfusion

# kubectl rollout status deployment/httpd-deploy --namespace=xfusion



