# # Deploy Jenkins on Kubernetes
# The Nautilus DevOps team is planning to set up a Jenkins CI server to create/manage some deployment pipelines for some of the projects. 
# They want to set up the Jenkins server on Kubernetes cluster. Below you can find more details about the task:


# 1) Create a namespace jenkins

# 2) Create a Service for jenkins deployment. Service name should be jenkins-service under jenkins namespace, type should be NodePort, nodePort should be 30008

# 3) Create a Jenkins Deployment under jenkins namespace, It should be name as jenkins-deployment , labels app should be jenkins , 
# container name should be jenkins-container , use jenkins/jenkins image , containerPort should be 8080 and replicas count should be 1.


apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins-container
          image: jenkins/jenkins
          ports:
            - containerPort: 8080


# # Check namespaces
# kubectl get namespaces

# # Check services in the jenkins namespace
# kubectl get services -n jenkins

# # Check deployments in the jenkins namespace
# kubectl get deployments -n jenkins
