apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins-container
          image: jenkins/jenkins
          ports:
            - containerPort: 8080


# # Check namespaces
# kubectl get namespaces

# # Check services in the jenkins namespace
# kubectl get services -n jenkins

# # Check deployments in the jenkins namespace
# kubectl get deployments -n jenkins
