# Deploy Grafana on Kubernetes Cluster

# The Nautilus DevOps teams is planning to set up a Grafana tool to collect and analyze analytics from some applications. 
# They are planning to deploy it on Kubernetes cluster. Below you can find more details.



# 1.) Create a deployment named grafana-deployment-xfusion using any grafana image for Grafana app. Set other parameters as per your choice.


# 2.) Create NodePort type service with nodePort 32000 to expose the app.


# You need not to make any configuration changes inside the Grafana app once deployed, just make sure you are able to access the Grafana login page.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest  # Use any Grafana image you prefer
        ports:
        - containerPort: 3000  # Grafana default port
        # You can add more configuration options here as needed
