# # Deploy Jenkins on Kubernetes
# The Nautilus DevOps team is planning to set up a Jenkins CI server to create/manage some deployment pipelines for some of the projects. 
# They want to set up the Jenkins server on Kubernetes cluster. Below you can find more details about the task:


# 1) Create a namespace jenkins

# 2) Create a Service for jenkins deployment. Service name should be jenkins-service under jenkins namespace, type should be NodePort, nodePort should be 30008

# 3) Create a Jenkins Deployment under jenkins namespace, It should be name as jenkins-deployment , labels app should be jenkins , 
# container name should be jenkins-container , use jenkins/jenkins image , containerPort should be 8080 and replicas count should be 1.


# First we will create an jenkins-namespace

apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
