# Create Deployments in Kubernetes Cluster
comment : >
  The Nautilus DevOps team has started practicing some pods and services deployment on Kubernetes platform, as they are planning to migrate most of their applications on Kubernetes. Recently one of the team members has been assigned a task to create a deployment as per details mentioned below:
  Create a deployment named httpd to deploy the application httpd using the image httpd:latest (remember to mention the tag as well)
  Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.

# run $ k create deployment httpd --image=httpd:latest
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-05-03T15:00:06Z"
  generation: 1
  labels:
    app: httpd
  name: httpd
  namespace: default
  resourceVersion: "6440"
  uid: bf0b8193-0347-4c0d-9420-65a88c016d5b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd:latest
        imagePullPolicy: Always
        name: httpd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-03T15:00:26Z"
    lastUpdateTime: "2024-05-03T15:00:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-03T15:00:06Z"
    lastUpdateTime: "2024-05-03T15:00:26Z"
    message: ReplicaSet "httpd-69545969bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
